site_name: Github User Documentation

nav:
    - Home: 'index.md'
    - 'Creating your first repository': 'Creating a repository.md'
    - 'Customizing your GitHub': 'Customizing your Github.md'
    - 'Working with Git': 'Working with Git.md'
    - 'Troubleshooting': 'troubleshooting.md'
    - 'Glossary' : 'glossary.md'


theme:
  name: material
  features: content.code.copy



  palette:

 # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


